"""
src/hypothesis/llm_suggest.py — LLM-based hypothesis expansion (optional, behind flag).

Per 09_LLM_ARCHITECTURE.md §4 and 13_BACKEND_MODULE_PLAN.md §4:
  LLM suggestions are NON-AUTHORITATIVE — they are additive candidates
  that the rule engine did not surface. They are never promoted to Strong confidence
  without structured evidence validation.

This module is DISABLED by default and only enabled when:
  - LLM_SUGGEST_ENABLED=true (environment variable)
  - A real LLM provider is configured (not mock)

When disabled: returns an empty list — the pipeline is unaffected.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

from src.hypothesis.rules import HypothesisCandidate
from src.llm.llm_client import call


# ── Config flag ────────────────────────────────────────────────────────────

def _is_enabled() -> bool:
    return os.environ.get("LLM_SUGGEST_ENABLED", "false").lower() == "true"


# ── Output type ────────────────────────────────────────────────────────────

@dataclass
class LLMSuggestedHypothesis:
    """
    Non-authoritative hypothesis suggestion from LLM.
    Must NOT be ranked alongside rule-based candidates without evidence validation.
    """
    driver: str
    rationale: str
    confidence_label: str = "LLM-Suggested (unvalidated)"
    requires_validation: bool = True


# ── Expansion logic ────────────────────────────────────────────────────────

def suggest_additional_hypotheses(
    kpi_name: str,
    affected_segment: str,
    existing_drivers: list[str],
) -> list[LLMSuggestedHypothesis]:
    """
    Ask the LLM to suggest additional root-cause hypotheses not already covered
    by the rule engine. Returns empty list when feature is disabled.

    Args:
        kpi_name:          e.g. "Revenue"
        affected_segment:  e.g. "North / Electronics"
        existing_drivers:  list of driver names already generated by the rule engine

    Returns:
        List of LLMSuggestedHypothesis (may be empty)
    """
    if not _is_enabled():
        return []

    system = (
        "You are a business intelligence assistant. "
        "Suggest additional root causes for a KPI anomaly not already covered by the list given. "
        "Return a JSON array of {driver, rationale} objects. "
        "Maximum 2 suggestions. Do not repeat existing drivers. "
        "These are hypotheses only — do not state confidence levels."
    )

    prompt = (
        f"KPI: {kpi_name}\n"
        f"Affected segment: {affected_segment}\n"
        f"Existing drivers already being investigated: {existing_drivers}\n\n"
        "Suggest up to 2 additional root causes not in the list above. "
        "Return only valid JSON array."
    )

    resp = call(prompt, system)
    if not resp.success:
        return []

    try:
        # Strip markdown code fences if present
        text = resp.text.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        suggestions = json.loads(text.strip())
        return [
            LLMSuggestedHypothesis(
                driver=s.get("driver", "Unknown"),
                rationale=s.get("rationale", ""),
            )
            for s in suggestions
            if isinstance(s, dict)
        ]
    except (json.JSONDecodeError, TypeError):
        return []
